# Generated by Django 5.2.4 on 2025-07-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='libraryuser',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
