# Generated by Django 5.2.4 on 2025-07-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_alter_libraryuser_email_alter_libraryuser_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_num', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.CharField(max_length=100)),
                ('created_At', models.DateTimeField()),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='book_images/')),
                ('price', models.FloatField()),
            ],
        ),
    ]
