# Generated by Django 5.2.4 on 2025-08-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_contactus_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryuser',
            name='role',
            field=models.CharField(choices=[('A', 'admin'), ('U', 'user')], default='U', max_length=1),
        ),
    ]
