# Generated by Django 5.2.4 on 2025-08-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0008_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
