# Generated by Django 5.2.4 on 2025-08-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0009_alter_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_num',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
