# Generated by Django 5.2.4 on 2025-08-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0011_remove_book_user_bookrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=10),
        ),
    ]
