# Generated by Django 5.2.4 on 2025-08-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0013_alter_bookrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
